### PR TITLE
v0.1.0

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by kozross** [comment]
Why not make the upper bound on base ``5``? I doubt very much anything could break severely enough in GHC 8.10 to warrant this library not building, and it avoids you having to do this bounds-related song-and-dance again in six months' time.

**Comment by sjakobi** [comment]
> Why not make the upper bound on base `5`? I doubt very much anything could break severely enough in GHC 8.10 to warrant this library not building, and it avoids you having to do this bounds-related song-and-dance again in six months' time.

Maybe not in GHC 8.10, but I don't know about GHC 8.12. If no changes are needed for the next GHC version, I can make a Hackage revision in ~60s.

**Comment by sjakobi** [comment]
Since you (re-)wrote most of the code in this package, I've added you as an author @treeowl.

**Comment by treeowl** [comment]
Thanks!

**Comment by sjakobi** [comment]
See http://hackage.haskell.org/package/coercible-utils-0.1.0.

**Pull request merged**
